backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: public/img
public_folder: img

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }

  - name: "content"
    label: "Content"
    files:
      - file: "src/pages/impressum/impressum.json"
        name: impressum
        label: "Impressum"
        fields:
          - name: categories
            label: "Imprint Categories"
            widget: list
            allow_add: true
            fields:
              - name: title
                label: "Title"
                widget: string
                required: false
              - name: content_de
                label: "Text"
                widget: text
          - name: contact
            label: "Kontakt"
            widget: text
          - name: press
            label: "Presse"
            widget: text

            # entweder so oder via artists projekte hinzufügen
      - file: "src/pages/partners/partners.json"
        name: partners
        label: "Partners"
        fields:
          - name: partners
            label: "Partners"
            widget: list
            allow_add: true
            fields:
              - name: title
                label: "Title"
                widget: string
              - name: link
                label: "Web Link"
                widget: string
              - name: image
                label: "Logo Image"
                widget: image
#       - file: "src/pages/timetable/timetable.json"
#         name: timetable
#         label: "Timetable"
#         fields:
#           - name: events
#             widget: list
#             allow_add: true
#             fields:
#               - name: artist
#                 required: false
#                 label: "Artist"
#                 widget: relation
#                 collection: "artists"
#                 value_field: title
#                 search_fields: [title]
