backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: public/img
public_folder: img

collections:
  # - name: "projects"
  #   label: "Projects"
  #   folder: "src/pages/projects"
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Category", name: "category", widget: "select", multiple: true, options: ["Auftragsarbeit", "Freie Arbeiten", "Vermittlung"] }
  #     - { label: "Thumbnail", name: "thumbnail", widget: image }
  #     - { label: "Details", name: "details", widget: "text" }
  #     - { label: "Description", name: "description", widget: "text" }
  - name: "content"
    label: "Content"
    files:
      - file: "pages/info/info.json"
        name: info
        label: "Info"
        fields:
          - name: title
            label: "Title"
            widget: string
          - name: mail
            label: "Mail"
            widget: string
          - name: phonenumber
            label: "Telefonnummer"
            widget: string
          - name: location
            label: "Location"
            widget: string
          - name: infoblocks
            label: "Infoblocks Text"
            widget: list
            allow_add: true
            fields:
              - name: subtitle
                label: "Subtitle"
                widget: string
                required: false
              - name: text
                label: "Text"
                widget: text
                required: false
      - file: "pages/projekt/projekt.json"
        name: projekt
        label: "Projekt"
        fields:
          - name: projekt
            label: "Projekt"
            widget: list
            allow_add: true
            fields:
              - name: title
                label: "Title"
                widget: string
              - name: "kategorie"
                label: "Kategorie"
                widget: "select"
                multiple: true
                options: ["Auftragsarbeit", "Freie Arbeiten", "Vermittlung"]
              - name: thumbnail
                label: "Thumbnail"
                widget: image
              - name: angaben
                label: "Angaben"
                widget: text
              - name: text
                label: "Text"
                widget: text
              - name: projektinhalt
                label: "Projektinhalt"
                widget: list
                allow_add: true
                required: false
                fields:
                  - name: image
                    label: "Image oder GIF"
                    widget: image
                    required: false
                    allow_add: true
                  - name: vimeolink
                    label: "Vimeolink"
                    widget: string
                    required: false
                    allow_add: true
      - file: "pages/fakeprojekt/fakeprojekt.json"
        name: fakeprojekt
        label: "Fakeprojekt"
        fields:
          - name: fakeprojekt
            label: "Fakeprojekt"
            widget: list
            allow_add: true
            fields:
              - name: title
                label: "Title"
                widget: string
              - name: "kategorie"
                label: "Kategorie"
                widget: "select"
                multiple: true
                options: ["Auftragsarbeit", "Freie Arbeiten", "Vermittlung"]
              - name: thumbnail
                label: "Thumbnail"
                widget: image
              - name: drehbild
                label: "Drehbild"
                widget: image