backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: public/img
public_folder: img

collections:
  # - name: "projects"
  #   label: "Projects"
  #   folder: "src/pages/projects"
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Category", name: "category", widget: "select", multiple: true, options: ["Auftragsarbeit", "Freie Arbeiten", "Vermittlung"] }
  #     - { label: "Thumbnail", name: "thumbnail", widget: image }
  #     - { label: "Details", name: "details", widget: "text" }
  #     - { label: "Description", name: "description", widget: "text" }
  #     - { label: "Image oben", name: "image", widget: image }
  #     - name: links
  #       label: "Links"
  #       widget: list
  #       allow_add: true
  #       required: false
  #       fields:
  #       - name: url
  #         label: URL
  #         widget: string
  #         required: false
  #         hint: "Entweder Bild oder url"
  #       - name: image
  #         label: Image
  #         widget: image
  #         required: false
      # - label: "Featured Image"
      #   name: "thumbnail-image"
      #   widget: "image"
      #   choose_url: true
      #   default: "/uploads/chocolate-dogecoin.jpg"
      #   media_library:
      #     config:
      #       multiple: true
      # - {label: "Draft", name: "draft", widget: "boolean", default: true}
  # - name: "artists"
  #   label: "Artists"
  #   folder: "src/pages/artists"
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - { label: "Template Key", name: "templateKey", widget: "hidden", default: "artist-page" }
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Date", name: "date", widget: "datetime" }
  #     - { label: "Location", name: "location", widget: "text" }
  #     - { label: "Description (DE)", name: "description_de", widget: "text" }
  #     - { label: "Description (EN)", name: "description_en", widget: "text" }
  #     - { label: "Image", name: "image", widget: image }
  #     - name: links
  #       label: "Links"
  #       widget: list
  #       allow_add: true
  #       required: false
  #       fields:
  #         - name: title
  #           label: Title
  #           widget: string
  #           hint: "Z.b.: 'FB', 'YT' etc."
  #         - name: url
  #           label: URL
  #           widget: string
  - name: "content"
    label: "Content"
    files:
      - file: "pages/info/info.json"
        name: info
        label: "Info"
        fields:
          - name: title
            label: "Title"
            widget: string
          - name: mail
            label: "Mail"
            widget: string
          - name: phonenumber
            label: "Telefonnummer"
            widget: string
          - name: location
            label: "Location"
            widget: string
          - name: infoblocks
            label: "Infoblocks Text"
            widget: list
            allow_add: true
            fields:
              - name: subtitle
                label: "Subtitle"
                widget: string
                required: false
              - name: text
                label: "Text"
                widget: text
                required: false
      - file: "pages/projekt/projekt.json"
        name: projekt
        label: "Projekt"
        fields:
          - name: projekt
            label: "Projekt"
            widget: list
            allow_add: true
            fields:
              - name: title
                label: "Title"
                widget: string
              - name: "kategorie"
                label: "Kategorie"
                widget: "select"
                multiple: true
                options: ["Auftragsarbeit", "Freie Arbeiten", "Vermittlung"]
              - name: thumbnail
                label: "Thumbnail"
                widget: image
              - name: angaben
                label: "Angaben"
                widget: text
              - name: text
                label: "Text"
                widget: text
              # - name: projektinhalt
              #   label: "Projektinhalt"
              #   widget: list
              #   allow_add: true
              #   required: false
              #   fields:
              #     - name: image
              #       label: "Image oder GIF"
              #       widget: image
              #       required: false
              #       allow_add: true
              #     - name: vimeolink
              #       label: "Vimeolink"
              #       widget: string
              #       required: false
              #       allow_add: true
      - file: "pages/fakeprojekt/fakeprojekt.json"
        name: fakeprojekt
        label: "Fakeprojekt"
        fields:
          - name: fakeprojekt
            label: "Fakeprojekt"
            widget: list
            allow_add: true
            fields:
              - name: title
                label: "Title"
                widget: string
              - name: "kategorie"
                label: "Kategorie"
                widget: "select"
                multiple: true
                options: ["Auftragsarbeit", "Freie Arbeiten", "Vermittlung"]
              - name: thumbnail
                label: "Thumbnail"
                widget: image
              - name: drehbild
                label: "Drehbild"
                widget: image